version: '2'
services:
    salesorder-postgresql:
        container_name: salesorder-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/SalesOrder/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=SalesOrder
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
